# Generated by Django 5.2.15 on 2026-06-07 16:16

import share.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Full identifier, e.g. is.workflow.actions.something",
                        max_length=200,
                        unique=True,
                        verbose_name="Action Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "category",
                    models.CharField(
                        default="SHORTCUTS", max_length=50, verbose_name="Category"
                    ),
                ),
                (
                    "glyph",
                    models.CharField(
                        default="Magic.svg",
                        help_text="A file name from staticfiles/assets/cat/, e.g. Web.svg",
                        max_length=60,
                        verbose_name="Glyph file",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What the action outputs, if anything (leave blank for none).",
                        max_length=100,
                        verbose_name="Result name",
                    ),
                ),
                (
                    "title_spec",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Title segments"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
        migrations.CreateModel(
            name="Shortcut",
            fields=[
                (
                    "iCloud",
                    models.URLField(
                        help_text="iCloud link created by Sharing your Shortcut",
                        max_length=100,
                        verbose_name="iCloud link",
                    ),
                ),
                (
                    "iCloudID",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="iCloud ID",
                    ),
                ),
                (
                    "download_link",
                    models.URLField(max_length=600, verbose_name="Download Link"),
                ),
                (
                    "action_blocks",
                    share.models.JSONField(
                        default=dict, verbose_name="Shortcut Actions"
                    ),
                ),
                (
                    "UUID_glyphs",
                    share.models.JSONField(default=dict, verbose_name="UUID Glyphs"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "glyphID",
                    models.PositiveIntegerField(default=59771, verbose_name="Glyph ID"),
                ),
                (
                    "colorID",
                    models.PositiveIntegerField(
                        default=431817727, verbose_name="Color ID"
                    ),
                ),
                (
                    "workflow_version",
                    models.IntegerField(default=0, verbose_name="Workflow Version"),
                ),
                (
                    "shortcut_types",
                    models.CharField(
                        default="", max_length=200, verbose_name="Shortcut Types"
                    ),
                ),
                (
                    "accepted_types",
                    models.CharField(
                        default="", max_length=1000, verbose_name="Accepts"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created On"),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
