# Generated by Django 5.2.15 on 2026-06-06 20:29

import share.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0014_auto_20191212_1808"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="UUID_glyphs",
            field=share.models.JSONField(default=dict, verbose_name="UUID Glyphs"),
        ),
        migrations.AlterField(
            model_name="shortcut",
            name="action_blocks",
            field=share.models.JSONField(default=dict, verbose_name="Shortcut Actions"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
