# Generated by Django 5.2.15 on 2026-06-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0015_modernize_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Full identifier, e.g. is.workflow.actions.something",
                        max_length=200,
                        unique=True,
                        verbose_name="Action Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "category",
                    models.CharField(
                        default="SHORTCUTS", max_length=50, verbose_name="Category"
                    ),
                ),
                (
                    "glyph",
                    models.CharField(
                        default="Magic.svg",
                        help_text="A file name from staticfiles/assets/cat/, e.g. Web.svg",
                        max_length=60,
                        verbose_name="Glyph file",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What the action outputs, if anything (leave blank for none).",
                        max_length=100,
                        verbose_name="Result name",
                    ),
                ),
                (
                    "title_spec",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Title segments"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
    ]
